# frontend/cloudbuild.yaml
steps:
  # Get backend URL (if needed at build time)
  - id: 'get-backend-url'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe api-dev \
            --region=us-central1 \
            --format=json \
            | jq -r '.status.url' > /workspace/backend_url.txt

  - id: 'build-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:latest'
      - '.'
    dir: 'frontend'

  - id: 'push-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/frontend'

  - id: 'deploy-frontend'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        gcloud run deploy frontend-dev \
          --image=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --update-env-vars="VITE_API_URL=$BACKEND_URL"

images:
  - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/frontend:latest'

timeout: '900s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'